name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          file_name: .env
          fail_on_empty: false

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email jlsk25@gmail.com
          git config --global user.name Joao Kestering
          git status
          git remote add origin https://${{secrets.token}}@github.com/joaoluizSK/nasa_apis.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
