name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: example/nasa-api

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          file_name: .env
          fail_on_empty: false
          directory: example/nasa-api

      - name: Build Web
        run: |
          cd example/nasa-api
          flutter build web --web-renderer html --base-href='/nasa-api/' --release

      - name: "Deploy web app"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/nasa-api/build/web
